# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsuser',
            name='login_date',
            field=models.DateField(null=True, verbose_name='\u4e0a\u6b21\u767b\u5f55\u65f6\u95f4'),
        ),
    ]
