# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170831_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsuser',
            name='login_date',
        ),
        migrations.AlterField(
            model_name='cmsuser',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
