# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170831_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cmsuser',
            name='is_admin',
        ),
    ]
