# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170831_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AddField(
            model_name='cmsuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u8d85\u7ea7\u7ba1\u7406\u5458'),
        ),
    ]
