# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170929_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
