# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170930_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(blank=True, verbose_name='\u6458\u8981')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(1, '\u53d1\u5e03'), (2, '\u8349\u7a3f\u7bb1')], default=1, verbose_name='\u72b6\u6001')),
                ('comments_count', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('view_count', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-published_date'],
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
