# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
