# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171012_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '\u8be5\u6635\u79f0\u88ab\u5360\u7528'}, max_length=50, unique=True, verbose_name='nickname'),
        ),
    ]
