# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170831_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsuser',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
