# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u4f5c\u8005'),
        ),
    ]
