# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170901_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsuser',
            name='avatar',
            field=models.ImageField(default='default.png', max_length=200, upload_to='avatar/%Y/%m/%d', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='cmsuser',
            name='profile',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb'),
        ),
    ]
