# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('user_id', models.IntegerField(default=0, editable=False, verbose_name='\u4f5c\u8005')),
                ('img', models.ImageField(upload_to='article/', verbose_name='\u9996\u9875\u5c55\u793a\u56fe\u7247')),
                ('img_is_centent_show', models.SmallIntegerField(choices=[(1, '\u5c55\u793a'), (0, '\u4e0d\u5c55\u793a')], default=0, verbose_name='\u9996\u9875\u56fe\u7247\u662f\u5426\u5728\u6587\u7ae0\u9876\u7aef\u5c55\u793a')),
                ('desc', models.TextField(blank=True, verbose_name='\u6458\u8981')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(1, '\u53d1\u5e03'), (2, '\u8349\u7a3f\u7bb1')], default=1, verbose_name='\u72b6\u6001')),
                ('comments_count', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('view_count', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570')),
            ],
            options={
                'ordering': ['-published_date'],
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('sort', models.SmallIntegerField(default=1, verbose_name='\u5206\u7c7b\u6392\u5e8f')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='\u7236\u7ea7\u8bc4\u8bba')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('sort', models.SmallIntegerField(default=1, verbose_name='\u5206\u7c7b\u6392\u5e8f')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
