# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:06
from __future__ import unicode_literals

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
