# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='imgs/', verbose_name='\u56fe\u7247')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u7b80\u5355\u63cf\u8ff0')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('user_id', models.IntegerField(default=0, editable=False, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u8d44\u6e90',
                'verbose_name_plural': '\u56fe\u7247\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='ImgsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('sort', models.SmallIntegerField(default=1, verbose_name='\u5206\u7c7b\u6392\u5e8f')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='imgs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='img.ImgsTag', verbose_name='\u56fe\u7247\u6807\u7b7e'),
        ),
    ]
