# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20171115_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='img_url',
            field=models.ImageField(upload_to='imgage/', verbose_name='\u56fe\u7247'),
        ),
    ]
